import { CharacterClass } from '../collections/CharacterClass';

export const CHARACTER_CLASSES: CharacterClass[] = [
  {
    key: 'STR_GENERAL',
    type: 'PERK',
    attributeKey: 'STR',
    name: 'Strong',
    color: '#494949',
    order: 1,
    featureKeys: [
      'STR_GENERAL_F1',
      'STR_GENERAL_F2',
      'STR_GENERAL_F3',
      'STR_GENERAL_F4',
      'STR_GENERAL_F5',
      'STR_GENERAL_F6',
      'STR_GENERAL_F7',
    ],
  },
  {
    key: 'AGI_GENERAL',
    type: 'PERK',
    attributeKey: 'AGI',
    name: 'Agile',
    color: '#494949',
    order: 1,
    featureKeys: [
      'AGI_GENERAL_F1',
      'AGI_GENERAL_F2',
      'AGI_GENERAL_F3',
      'AGI_GENERAL_F4',
      'AGI_GENERAL_F5',
      'AGI_GENERAL_F6',
    ],
  },
  {
    key: 'INT_GENERAL',
    type: 'PERK',
    attributeKey: 'INT',
    name: 'Knowledgable',
    color: '#494949',
    order: 1,
    featureKeys: [
      'INT_GENERAL_F1',
      'INT_GENERAL_F2',
      'INT_GENERAL_F3',
      'INT_GENERAL_F4',
      'INT_GENERAL_F5',
      'INT_GENERAL_F6',
    ],
  },
  {
    key: 'CHA_GENERAL',
    type: 'PERK',
    attributeKey: 'CHA',
    name: 'Charismatic',
    color: '#494949',
    order: 1,
    featureKeys: [
      'CHA_GENERAL_F1',
      'CHA_GENERAL_F2',
      'CHA_GENERAL_F3',
      'CHA_GENERAL_F4',
      'CHA_GENERAL_F5',
      'CHA_GENERAL_F6',
    ],
  },
  {
    key: 'WIS_GENERAL',
    type: 'PERK',
    attributeKey: 'WIS',
    name: 'Instinctual',
    color: '#494949',
    order: 1,
    featureKeys: [
      'WIS_GENERAL_F1',
      'WIS_GENERAL_F2',
      'WIS_GENERAL_F3',
      'WIS_GENERAL_F4',
      'WIS_GENERAL_F5',
      'WIS_GENERAL_F6',
      'WIS_GENERAL_F7',
    ],
  },
  {
    key: 'WIS_SAGE1',
    type: 'CLASS',
    attributeKey: 'WIS',
    name: 'Storm Sage',
    color: '#3799d1',
    order: 2,
    ascendable: true,
    featureKeys: [
      'WIS_SAGE1_F1',
      'WIS_SAGE1_F2',
      'WIS_SAGE1_F3',
      'WIS_SAGE1_F4',
      'WIS_SAGE1_F5',
      'WIS_SAGE1_F6',
    ],
  },
  {
    key: 'WIS_DRUID1',
    type: 'CLASS',
    attributeKey: 'WIS',
    name: 'Beast Druid',
    color: '#d16337',
    order: 3,
    ascendable: true,
    featureKeys: [
      'WIS_DRUID1_F1',
      'WIS_DRUID1_F2',
      'WIS_DRUID1_F3',
      'WIS_DRUID1_F4',
      'WIS_DRUID1_F5',
      'WIS_DRUID1_F6',
    ],
  },
  {
    key: 'WEAPON_SWORD',
    type: 'WEAPON',
    attributeKey: 'STR',
    name: 'Sword',
    color: '#888888',
    order: 1,
    ascendable: true,
    featureKeys: [
      'WEAPON_SWORD_F1',
      'WEAPON_SWORD_R1_STONE',
      'WEAPON_SWORD_R2_STONE',
      'WEAPON_SWORD_R3_STONE',
      'WEAPON_SWORD_R4_STONE',
      'WEAPON_SWORD_R5_STONE',
      'WEAPON_SWORD_R1_SKY',
      'WEAPON_SWORD_R2_SKY',
      'WEAPON_SWORD_R3_SKY',
      'WEAPON_SWORD_R4_SKY',
      'WEAPON_SWORD_R5_SKY',
      'WEAPON_SWORD_R1_SUN',
      'WEAPON_SWORD_R2_SUN',
      'WEAPON_SWORD_R3_SUN',
      'WEAPON_SWORD_R4_SUN',
      'WEAPON_SWORD_R5_SUN',
      'WEAPON_SWORD_R1_MOON',
      'WEAPON_SWORD_R2_MOON',
      'WEAPON_SWORD_R3_MOON',
      'WEAPON_SWORD_R4_MOON',
      'WEAPON_SWORD_R5_MOON',
      'WEAPON_SWORD_R1_SPIRIT',
      'WEAPON_SWORD_R2_SPIRIT',
      'WEAPON_SWORD_R3_SPIRIT',
      'WEAPON_SWORD_R4_SPIRIT',
      'WEAPON_SWORD_R5_SPIRIT',
    ],
  },
  {
    key: 'WEAPON_BOW',
    type: 'WEAPON',
    attributeKey: 'STR',
    name: 'Bow',
    color: '#888888',
    order: 2,
    ascendable: true,
    featureKeys: ['WEAPON_BOW_F1'],
  },
  {
    key: 'WEAPON_STAFF',
    type: 'WEAPON',
    attributeKey: 'STR',
    name: 'Staff',
    color: '#888888',
    order: 3,
    ascendable: true,
    featureKeys: ['WEAPON_STAFF_F1'],
  },
  {
    key: 'ARMOR_HEAVY',
    type: 'ARMOR',
    name: 'Plate',
    color: '#888888',
    order: 1,
    ascendable: true,
    featureKeys: ['ARMOR_HEAVY_F1', 'ARMOR_HEAVY_F2'],
  },
  {
    key: 'ARMOR_LIGHT',
    type: 'ARMOR',
    name: 'Leathers',
    color: '#888888',
    order: 2,
    ascendable: true,
    featureKeys: ['ARMOR_LIGHT_F1', 'ARMOR_LIGHT_F2', 'ARMOR_LIGHT_F3'],
  },
  {
    key: 'ARMOR_NONE',
    type: 'ARMOR',
    name: 'Robe',
    color: '#888888',
    order: 3,
    featureKeys: [
      'ARMOR_NONE_F1',
      'ARMOR_NONE_F2',
      'ARMOR_NONE_F3',
      'ARMOR_NONE_F4',
      'ARMOR_NONE_F5',
      'ARMOR_NONE_F6',
    ],
  },
];
