import { CharacterClass } from '../collections/CharacterClass';

export const CHARACTER_CLASSES: CharacterClass[] = [
  {
    key: 'STR_GENERAL',
    type: 'PERK',
    attributeKey: 'STR',
    name: 'Strong',
    color: '#494949',
    order: 1,
    featureKeys: [
      'STR_GENERAL_F1',
      'STR_GENERAL_F2',
      'STR_GENERAL_F3',
      'STR_GENERAL_F4',
      'STR_GENERAL_F5',
      'STR_GENERAL_F6',
      'STR_GENERAL_F7',
    ],
  },
  {
    key: 'AGI_GENERAL',
    type: 'PERK',
    attributeKey: 'AGI',
    name: 'Agile',
    color: '#494949',
    order: 1,
    featureKeys: [
      'AGI_GENERAL_F1',
      'AGI_GENERAL_F2',
      'AGI_GENERAL_F3',
      'AGI_GENERAL_F4',
      'AGI_GENERAL_F5',
      'AGI_GENERAL_F6',
    ],
  },
  {
    key: 'INT_GENERAL',
    type: 'PERK',
    attributeKey: 'INT',
    name: 'Knowledgeable',
    color: '#494949',
    order: 1,
    featureKeys: [
      'INT_GENERAL_F1',
      'INT_GENERAL_F2',
      'INT_GENERAL_F3',
      'INT_GENERAL_F4',
      'INT_GENERAL_F5',
      'INT_GENERAL_F6',
    ],
  },
  {
    key: 'CHA_GENERAL',
    type: 'PERK',
    attributeKey: 'CHA',
    name: 'Charismatic',
    color: '#494949',
    order: 1,
    featureKeys: [
      'CHA_GENERAL_F1',
      'CHA_GENERAL_F2',
      'CHA_GENERAL_F3',
      'CHA_GENERAL_F4',
      'CHA_GENERAL_F5',
      'CHA_GENERAL_F6',
    ],
  },
  {
    key: 'WIS_GENERAL',
    type: 'PERK',
    attributeKey: 'WIS',
    name: 'Instinctual',
    color: '#494949',
    order: 1,
    featureKeys: [
      'WIS_GENERAL_F1',
      'WIS_GENERAL_F2',
      'WIS_GENERAL_F3',
      'WIS_GENERAL_F4',
      'WIS_GENERAL_F5',
      'WIS_GENERAL_F6',
      'WIS_GENERAL_F7',
    ],
  },
  {
    key: 'STR_KNIGHT',
    type: 'CLASS',
    attributeKey: 'STR',
    name: 'Vanguard Knight',
    color: '#336fca',
    order: 1,
    ascendable: true,
    featureKeys: [
      'STR_KNIGHT_F1',
      'STR_KNIGHT_F2',
      'STR_KNIGHT_F3',
      'STR_KNIGHT_F4',
      'STR_KNIGHT_F5',
      'STR_KNIGHT_F6',
    ],
  },
  {
    key: 'STR_BARBARIAN',
    type: 'CLASS',
    attributeKey: 'STR',
    name: 'Berserker Barbarian',
    color: '#ca3333',
    order: 2,
    ascendable: true,
    featureKeys: [
      'STR_BARBARIAN_F1',
      'STR_BARBARIAN_F2',
      'STR_BARBARIAN_F3',
      'STR_BARBARIAN_F4',
      'STR_BARBARIAN_F5',
      'STR_BARBARIAN_F6',
    ],
  },
  {
    key: 'AGI_RANGER',
    type: 'CLASS',
    attributeKey: 'AGI',
    name: 'Marksman Ranger',
    color: '#0d7535',
    order: 1,
    ascendable: true,
    featureKeys: [
      'AGI_RANGER_F1',
      'AGI_RANGER_F2',
      'AGI_RANGER_F3',
      'AGI_RANGER_F4',
      'AGI_RANGER_F5',
      'AGI_RANGER_F6',
    ],
  },
  {
    key: 'AGI_SAGE',
    type: 'CLASS',
    attributeKey: 'AGI',
    name: 'Storm Sage',
    color: '#3799d2',
    order: 2,
    ascendable: true,
    featureKeys: [
      'AGI_SAGE_F1',
      'AGI_SAGE_F2',
      'AGI_SAGE_F3',
      'AGI_SAGE_F4',
      'AGI_SAGE_F5',
      'AGI_SAGE_F6',
    ],
  },
  {
    key: 'INT_MAGE',
    type: 'CLASS',
    attributeKey: 'INT',
    name: 'Guardian Mage',
    color: '#f1c645',
    order: 1,
    ascendable: true,
    featureKeys: [
      'INT_MAGE_F1',
      'INT_MAGE_F2',
      'INT_MAGE_F3',
      'INT_MAGE_F4',
      'INT_MAGE_F5',
      'INT_MAGE_F6',
    ],
  },
  {
    key: 'INT_MANCER',
    type: 'CLASS',
    attributeKey: 'INT',
    name: 'Mechanist Mancer',
    color: '#a186d3',
    order: 2,
    ascendable: true,
    featureKeys: [
      'INT_MANCER_F1',
      'INT_MANCER_F2',
      'INT_MANCER_F3',
      'INT_MANCER_F4',
      'INT_MANCER_F5',
      'INT_MANCER_F6',
    ],
  },
  {
    key: 'CHA_HERALD',
    type: 'CLASS',
    attributeKey: 'CHA',
    name: 'Leader Herald',
    color: '#33ca6d',
    order: 1,
    ascendable: true,
    featureKeys: [
      'CHA_HERALD_F1',
      'CHA_HERALD_F2',
      'CHA_HERALD_F3',
      'CHA_HERALD_F4',
      'CHA_HERALD_F5',
      'CHA_HERALD_F6',
    ],
  },
  {
    key: 'CHA_CHANTER',
    type: 'CLASS',
    attributeKey: 'CHA',
    name: 'Corruption Chanter',
    color: '#5e28c2',
    order: 2,
    ascendable: true,
    featureKeys: [
      'CHA_CHANTER_F1',
      'CHA_CHANTER_F2',
      'CHA_CHANTER_F3',
      'CHA_CHANTER_F4',
      'CHA_CHANTER_F5',
      'CHA_CHANTER_F6',
    ],
  },
  {
    key: 'WIS_MONK',
    type: 'CLASS',
    attributeKey: 'WIS',
    name: 'Devote Monk',
    color: '#689c7e',
    order: 1,
    ascendable: true,
    featureKeys: [
      'WIS_MONK_F1',
      'WIS_MONK_F2',
      'WIS_MONK_F3',
      'WIS_MONK_F4',
      'WIS_MONK_F5',
      'WIS_MONK_F6',
    ],
  },
  {
    key: 'WIS_DRUID',
    type: 'CLASS',
    attributeKey: 'WIS',
    name: 'Beast Druid',
    color: '#d16337',
    order: 2,
    ascendable: true,
    featureKeys: [
      'WIS_DRUID_F1',
      'WIS_DRUID_F2',
      'WIS_DRUID_F3',
      'WIS_DRUID_F4',
      'WIS_DRUID_F5',
      'WIS_DRUID_F6',
    ],
  },
  {
    key: 'WEAPON_SWORD',
    type: 'WEAPON',
    attributeKey: 'STR',
    name: 'Sword',
    description: 'A one-handed melee weapon with a 5ft range.',
    color: '#888888',
    order: 1,
    ascendable: true,
    featureKeys: [
      'WEAPON_SWORD_F1',
      'WEAPON_SWORD_R1_STONE',
      'WEAPON_SWORD_R2_STONE',
      'WEAPON_SWORD_R3_STONE',
      'WEAPON_SWORD_R1_SKY',
      'WEAPON_SWORD_R2_SKY',
      'WEAPON_SWORD_R3_SKY',
      'WEAPON_SWORD_R1_SUN',
      'WEAPON_SWORD_R2_SUN',
      'WEAPON_SWORD_R3_SUN',
      'WEAPON_SWORD_R1_MOON',
      'WEAPON_SWORD_R2_MOON',
      'WEAPON_SWORD_R3_MOON',
      'WEAPON_SWORD_R1_SPIRIT',
      'WEAPON_SWORD_R2_SPIRIT',
      'WEAPON_SWORD_R3_SPIRIT',
    ],
  },
  {
    key: 'WEAPON_BOW',
    type: 'WEAPON',
    attributeKey: 'STR',
    name: 'Bow',
    description: 'A two-handed ranged weapon with a 10ft - 60ft range.',
    color: '#888888',
    order: 2,
    ascendable: true,
    featureKeys: [
      'WEAPON_BOW_F1',
      'WEAPON_BOW_R1_STONE',
      'WEAPON_BOW_R2_STONE',
      'WEAPON_BOW_R3_STONE',
      'WEAPON_BOW_R1_SKY',
      'WEAPON_BOW_R2_SKY',
      'WEAPON_BOW_R3_SKY',
      'WEAPON_BOW_R1_SUN',
      'WEAPON_BOW_R2_SUN',
      'WEAPON_BOW_R3_SUN',
      'WEAPON_BOW_R1_MOON',
      'WEAPON_BOW_R2_MOON',
      'WEAPON_BOW_R3_MOON',
      'WEAPON_BOW_R1_SPIRIT',
      'WEAPON_BOW_R2_SPIRIT',
      'WEAPON_BOW_R3_SPIRIT',
    ],
  },
  {
    key: 'WEAPON_STAFF',
    type: 'WEAPON',
    attributeKey: 'STR',
    name: 'Staff',
    description: 'A two-handed melee weapon with a 10ft range.',
    color: '#888888',
    order: 3,
    ascendable: true,
    featureKeys: [
      'WEAPON_STAFF_F1',
      'WEAPON_STAFF_R1_STONE',
      'WEAPON_STAFF_R2_STONE',
      'WEAPON_STAFF_R3_STONE',
      'WEAPON_STAFF_R1_SKY',
      'WEAPON_STAFF_R2_SKY',
      'WEAPON_STAFF_R3_SKY',
      'WEAPON_STAFF_R1_SUN',
      'WEAPON_STAFF_R2_SUN',
      'WEAPON_STAFF_R3_SUN',
      'WEAPON_STAFF_R1_MOON',
      'WEAPON_STAFF_R2_MOON',
      'WEAPON_STAFF_R3_MOON',
      'WEAPON_STAFF_R1_SPIRIT',
      'WEAPON_STAFF_R2_SPIRIT',
      'WEAPON_STAFF_R3_SPIRIT',
    ],
  },
  {
    key: 'ARMOR_HEAVY',
    type: 'ARMOR',
    name: 'Heavy',
    description: 'Heavy armor that is strong against physical attacks.',
    color: '#888888',
    order: 1,
    ascendable: true,
    featureKeys: [
      'ARMOR_HEAVY_F1',
      'ARMOR_HEAVY_F2',
      'WEAPON_HEAVY_R1_STONE',
      'WEAPON_HEAVY_R2_STONE',
      'WEAPON_HEAVY_R3_STONE',
      'WEAPON_HEAVY_R4_STONE',
      'WEAPON_HEAVY_R5_STONE',
      'WEAPON_HEAVY_R1_SKY',
      'WEAPON_HEAVY_R2_SKY',
      'WEAPON_HEAVY_R3_SKY',
      'WEAPON_HEAVY_R4_SKY',
      'WEAPON_HEAVY_R5_SKY',
      'WEAPON_HEAVY_R1_SUN',
      'WEAPON_HEAVY_R2_SUN',
      'WEAPON_HEAVY_R3_SUN',
      'WEAPON_HEAVY_R4_SUN',
      'WEAPON_HEAVY_R5_SUN',
      'WEAPON_HEAVY_R1_MOON',
      'WEAPON_HEAVY_R2_MOON',
      'WEAPON_HEAVY_R3_MOON',
      'WEAPON_HEAVY_R4_MOON',
      'WEAPON_HEAVY_R5_MOON',
      'WEAPON_HEAVY_R1_SPIRIT',
      'WEAPON_HEAVY_R2_SPIRIT',
      'WEAPON_HEAVY_R3_SPIRIT',
      'WEAPON_HEAVY_R4_SPIRIT',
      'WEAPON_HEAVY_R5_SPIRIT',
    ],
  },
  {
    key: 'ARMOR_LIGHT',
    type: 'ARMOR',
    name: 'Light',
    description: 'Light armor that is balanced against both physical and magical attacks.',
    color: '#888888',
    order: 2,
    ascendable: true,
    featureKeys: ['ARMOR_LIGHT_F1', 'ARMOR_LIGHT_F2', 'ARMOR_LIGHT_F3'],
  },
  {
    key: 'ARMOR_NONE',
    type: 'ARMOR',
    name: 'Magic',
    description: 'Magic armor that is strong against magical attacks.',
    color: '#888888',
    order: 3,
    featureKeys: [
      'ARMOR_NONE_F1',
      'ARMOR_NONE_F2',
      'ARMOR_NONE_F3',
      'ARMOR_NONE_F4',
      'ARMOR_NONE_F5',
      'ARMOR_NONE_F6',
    ],
  },
];
